[build]
  command = "npm run build"
  publish = ".next"
  
  # Déclarer explicitement les variables d'environnement requises
  [build.environment]
    NEXT_PUBLIC_OPENAI_API_KEY = ""
    OPENAI_API_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirection pour les fichiers statiques de Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Redirection pour toutes les routes non trouvées vers la fonction Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
